version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: git-ssh-sign
    main: .
    binary: git-ssh-sign
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

brews:
  - name: git-ssh-sign
    repository:
      owner: ismaels
      name: homebrew-gss-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/ismaels/git-ssh-sign"
    description: "Interactive wizard to configure SSH commit signing for Git"
    license: "MIT"
    install: |
      bin.install "git-ssh-sign"
    test: |
      system "#{bin}/git-ssh-sign", "--help"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
